// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.order.dto;

public interface OrderPurchaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.order.dto.OrderPurchaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int64 totalPrice = 2;</code>
   * @return The totalPrice.
   */
  long getTotalPrice();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
