// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.order.dto;

public interface OrderCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.order.dto.OrderCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 money = 2;</code>
   * @return The money.
   */
  int getMoney();

  /**
   * <code>string commodity_code = 3;</code>
   * @return The commodityCode.
   */
  String getCommodityCode();
  /**
   * <code>string commodity_code = 3;</code>
   * @return The bytes for commodityCode.
   */
  com.google.protobuf.ByteString
      getCommodityCodeBytes();

  /**
   * <code>int32 count = 4;</code>
   * @return The count.
   */
  int getCount();
}
