// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.order.dto;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_order_dto_OrderCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_order_dto_OrderCreateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013order.proto\022\035com.vinci.flashsale.order" +
      ".dto\"[\n\022OrderCreateRequest\022\017\n\007user_id\030\001 " +
      "\001(\t\022\r\n\005money\030\002 \001(\005\022\026\n\016commodity_code\030\003 \001" +
      "(\t\022\r\n\005count\030\004 \001(\005B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vinci_flashsale_order_dto_OrderCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vinci_flashsale_order_dto_OrderCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_order_dto_OrderCreateRequest_descriptor,
        new String[] { "UserId", "Money", "CommodityCode", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
