// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.order.dto;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_order_dto_OrderPurchaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_order_dto_OrderPurchaseRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013order.proto\022\035com.vinci.flashsale.order" +
      ".dto\"O\n\024OrderPurchaseRequest\022\021\n\tproductI" +
      "d\030\001 \001(\003\022\022\n\ntotalPrice\030\002 \001(\003\022\020\n\010quantity\030" +
      "\003 \001(\005B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vinci_flashsale_order_dto_OrderPurchaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vinci_flashsale_order_dto_OrderPurchaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_order_dto_OrderPurchaseRequest_descriptor,
        new String[] { "ProductId", "TotalPrice", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
