// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_service.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.storage.api;

public final class StorageService {
  private StorageService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025storage_service.proto\022\037com.vinci.flash" +
      "sale.storage.api\032\rstorage.proto\032\014common." +
      "proto2\210\001\n\021StorageApiService\022s\n\010Decrease\022" +
      "7.com.vinci.flashsale.storage.dto.Storag" +
      "eDecreaseRequest\032..com.vinci.flashsale.c" +
      "ommon.dto.CommonResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vinci.flashsale.storage.dto.Storage.getDescriptor(),
          com.vinci.flashsale.common.dto.Common.getDescriptor(),
        });
    com.vinci.flashsale.storage.dto.Storage.getDescriptor();
    com.vinci.flashsale.common.dto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
