// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_service.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.storage.api;

public final class StorageService {
  private StorageService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025storage_service.proto\022\037com.vinci.flash" +
      "sale.storage.api\032\rstorage.proto\032\014common." +
      "proto2\377\001\n\021StorageApiService\022o\n\006Reduce\0225." +
      "com.vinci.flashsale.storage.dto.StorageR" +
      "educeRequest\032..com.vinci.flashsale.commo" +
      "n.dto.CommonResponse\022y\n\020CompensateReduce" +
      "\0225.com.vinci.flashsale.storage.dto.Stora" +
      "geReduceRequest\032..com.vinci.flashsale.co" +
      "mmon.dto.CommonResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vinci.flashsale.storage.dto.Storage.getDescriptor(),
          com.vinci.flashsale.common.dto.Common.getDescriptor(),
        });
    com.vinci.flashsale.storage.dto.Storage.getDescriptor();
    com.vinci.flashsale.common.dto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
