// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.account.api;

public final class AccountService {
  private AccountService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025account-service.proto\022\037com.vinci.flash" +
      "sale.account.api\032\raccount.proto\032\014common." +
      "proto2\210\001\n\021AccountApiService\022s\n\010Decrease\022" +
      "7.com.vinci.flashsale.account.dto.Accoun" +
      "tDecreaseRequest\032..com.vinci.flashsale.c" +
      "ommon.dto.CommonResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vinci.flashsale.account.dto.Account.getDescriptor(),
          com.vinci.flashsale.common.dto.Common.getDescriptor(),
        });
    com.vinci.flashsale.account.dto.Account.getDescriptor();
    com.vinci.flashsale.common.dto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
