// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.common.dto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_common_dto_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_common_dto_CommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_common_dto_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_common_dto_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014common.proto\022\036com.vinci.flashsale.comm" +
      "on.dto\032\031google/protobuf/any.proto\032\033googl" +
      "e/protobuf/empty.proto\"S\n\016CommonResponse" +
      "\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\"\n\004data\030" +
      "\003 \001(\0132\024.google.protobuf.Any\"\007\n\005EmptyB\"\n\036" +
      "com.vinci.flashsale.common.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_vinci_flashsale_common_dto_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vinci_flashsale_common_dto_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_common_dto_CommonResponse_descriptor,
        new String[] { "Code", "Message", "Data", });
    internal_static_com_vinci_flashsale_common_dto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vinci_flashsale_common_dto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_common_dto_Empty_descriptor,
        new String[] { });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
