// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.common.dto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.common.dto.Empty)
    com.google.protobuf.MessageOrBuilder {
}
