<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.vinci.flash-sale</groupId>
    <artifactId>flash-sale-dependency</artifactId>
    <version>1.0.0</version>
    <name>flash-sale-dependency</name>
    <packaging>pom</packaging>
    <description>flash-sale-dependency</description>

    <parent>
        <groupId>com.vinci</groupId>
        <artifactId>flash-sale</artifactId>
        <version>1.0.0</version>
    </parent>

    <modules>
        <module>flash-sale-dependency-redis</module>
        <module>flash-sale-dependency-mybatis</module>
    </modules>


</project>
