// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.account.dto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_account_dto_AccountReduceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_account_dto_AccountReduceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\raccount.proto\022\037com.vinci.flashsale.acc" +
      "ount.dto\":\n\024AccountReduceRequest\022\016\n\006user" +
      "Id\030\001 \001(\003\022\022\n\ntotalPrice\030\002 \001(\003B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vinci_flashsale_account_dto_AccountReduceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vinci_flashsale_account_dto_AccountReduceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_account_dto_AccountReduceRequest_descriptor,
        new String[] { "UserId", "TotalPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
