// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.account.dto;

public interface AccountDecreaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.account.dto.AccountDecreaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 money = 2;</code>
   * @return The money.
   */
  int getMoney();
}
