// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.account.dto;

public interface AccountReduceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.account.dto.AccountReduceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 totalPrice = 2;</code>
   * @return The totalPrice.
   */
  long getTotalPrice();
}
