// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.storage.dto;

public interface StorageDecreaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.storage.dto.StorageDecreaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commodityCode = 1;</code>
   * @return The commodityCode.
   */
  String getCommodityCode();
  /**
   * <code>string commodityCode = 1;</code>
   * @return The bytes for commodityCode.
   */
  com.google.protobuf.ByteString
      getCommodityCodeBytes();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
