// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.storage.dto;

public interface StorageReduceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vinci.flashsale.storage.dto.StorageReduceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
