// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.storage.dto;

public final class Storage {
  private Storage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vinci_flashsale_storage_dto_StorageDecreaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vinci_flashsale_storage_dto_StorageDecreaseRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rstorage.proto\022\037com.vinci.flashsale.sto" +
      "rage.dto\">\n\026StorageDecreaseRequest\022\025\n\rco" +
      "mmodityCode\030\001 \001(\t\022\r\n\005count\030\002 \001(\005B\002P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vinci_flashsale_storage_dto_StorageDecreaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vinci_flashsale_storage_dto_StorageDecreaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vinci_flashsale_storage_dto_StorageDecreaseRequest_descriptor,
        new String[] { "CommodityCode", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
