// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_serivce.proto

// Protobuf Java Version: 3.25.5
package com.vinci.flashsale.order.api;

public final class OrderSerivce {
  private OrderSerivce() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023order_serivce.proto\022\035com.vinci.flashsa" +
      "le.order.api\032\013order.proto\032\014common.proto2" +
      "\202\001\n\017OrderApiService\022o\n\010Purchase\0223.com.vi" +
      "nci.flashsale.order.dto.OrderPurchaseReq" +
      "uest\032..com.vinci.flashsale.common.dto.Co" +
      "mmonResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vinci.flashsale.order.dto.Order.getDescriptor(),
          com.vinci.flashsale.common.dto.Common.getDescriptor(),
        });
    com.vinci.flashsale.order.dto.Order.getDescriptor();
    com.vinci.flashsale.common.dto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
